security:
    encoders:
        LoginBundle\Entity\User: bcrypt
        LoginBundle\Entity\Customer: bcrypt
        LoginBundle\Security\User\WebserviceUser: bcrypt
        
    role_hierarchy:
        ROLE_CUSTOMER: [ROLE_CUSTOMER]
        ROLE_USER: [ROLE_USER, ROLE_CUSTOMER]
        ROLE_ADMIN: [ROLE_USER, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_MAKE_ADMINS]

    providers:
        database_users:
            entity: { class: LoginBundle:User }
            
    access_denied_url: /    
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/administrator/
            form_login:
                check_path: /administrator/login_check
                login_path: /administrator/login
                username_parameter: _email
                csrf_provider: security.csrf.token_manager
                
            logout:
                path: /administrator/logout
                target: /administrator/
            
            anonymous:    ~
            
            remember_me:
                key:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /administrator/
                
        customer:
            pattern: ^/
            anonymous:      ~
            
        
    access_control:
        - { path: ^/customer-area, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/customer/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administrator/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administrator/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administrator/logout, role: ROLE_USER }
        - { path: ^/administrator/admin, role: ROLE_ADMIN }
        - { path: ^/administrator/admin_show, role: ROLE_ADMIN }
        - { path: ^/administrator/admin_new, role: ROLE_ADMIN }
        - { path: ^/administrator/admin_create, role: ROLE_ADMIN }
        - { path: ^/administrator/admin_delete, role: ROLE_ADMIN }
        - { path: ^/administrator/admin_password, role: ROLE_ADMIN }
        - { path: ^/administrator/admin_edit, role: ROLE_ADMIN }
        - { path: ^/administrator/admin_update, role: ROLE_ADMIN }
        - { path: ^/administrator/admin_password_update, role: ROLE_ADMIN }
        - { path: ^/administrator/register, role: ROLE_ADMIN }
        - { path: ^/administrator/, role: ROLE_USER }
        - { path: ^/administrator/template, role: ROLE_ADMIN }
        - { path: ^/administrator/new-template, role: ROLE_USER }
        - { path: ^/administrator/edit-template, role: ROLE_USER }
        - { path: ^/administrator/client, role: ROLE_USER }
        - { path: ^/administrator/addclient, role: ROLE_USER }
        - { path: ^/administrator/econtract, role: ROLE_USER }
        - { path: ^/administrator/resend-econtract, role: ROLE_USER }
        - { path: ^/administrator/your-signature, role: ROLE_USER }
        - { path: ^/administrator/selfsignusethis, role: ROLE_USER }
        - { path: ^/administrator/ajaxsketch, role: ROLE_USER }
        - { path: ^/administrator/previewiframe, role: ROLE_USER }
        - { path: ^/administrator/ajaxpreviewnewwindow, role: ROLE_USER }
        - { path: ^/administrator/ajaxPreviewNewTemplate, role: ROLE_USER }
        - { path: ^/administrator/ajaxPreviewNewWindowNewTemplate, role: ROLE_USER }
        - { path: ^/administrator/ajaxPreviewNewWindowTemplate, role: ROLE_USER }
        - { path: ^/administrator/ajaxpreview, role: ROLE_USER }
        - { path: ^/administrator/ajaxpreviewtemplate, role: ROLE_USER }
        - { path: ^/administrator/ajaxopentemplate, role: ROLE_USER }
        - { path: ^/administrator/ajaxOpenTemplateIframe, role: ROLE_USER }
        - { path: ^/administrator/ajaxopensettings, role: ROLE_USER }
        - { path: ^/administrator/ajaxopencontract, role: ROLE_USER }
        - { path: ^/administrator/deletesign, role: ROLE_USER }
        - { path: ^/administrator/autocomplete, role: ROLE_USER }
        - { path: ^/administrator/initpreview, role: ROLE_USER }
        - { path: ^/administrator/template-settings, role: ROLE_USER }
        - { path: ^/administrator/usesettings, role: ROLE_USER }
        - { path: ^/administrator/settingsdelete, role: ROLE_USER }
        - { path: ^/administrator/settingsedit, role: ROLE_USER }
        - { path: ^/administrator/sentcontracts, role: ROLE_USER }
        - { path: ^/administrator/emailsettings, role: ROLE_USER }
        - { path: ^/administrator/activateemailsettings, role: ROLE_USER }
        - { path: ^/administrator/deleteemailsettings, role: ROLE_USER }
        - { path: ^/administrator/emailtemplate, role: ROLE_USER }
        - { path: ^/administrator/ajaxemailTemplate, role: ROLE_USER }
        - { path: ^/administrator/deleteEmailTemplate, role: ROLE_USER }
        - { path: ^/administrator/ajaxappendemail, role: ROLE_USER }
        - { path: ^/administrator/ajaxTokenDisable, role: ROLE_USER }
        - { path: ^/administrator/openclient, role: ROLE_USER }
        - { path: ^/administrator/editclient, role: ROLE_USER }
        - { path: ^/administrator/deletetemplate, role: ROLE_USER }
        - { path: ^/administrator/edit-email-template, role: ROLE_USER }
        - { path: ^/administrator/ajaxOpenContractIframe, role: ROLE_USER }
        - { path: ^/administrator/create-your-signature, role: ROLE_USER }
        - { path: ^/administrator/upload-your-signature, role: ROLE_USER }
        - { path: ^/administrator/company, role: ROLE_USER }
        - { path: ^/administrator/application-about, role: ROLE_USER }
        - { path: ^/administrator/application-contact, role: ROLE_USER }
        - { path: ^/customer, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/e-contract, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/access-denied, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/already-signed, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/signednote, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/customerajaxsketch, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/customerajaxpreviewcontract, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ajaxIframeView, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/about, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contact, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resendpdf, role: IS_AUTHENTICATED_ANONYMOUSLY }
 