login_customer:
    path:   /customer/{token}
    defaults: { _controller: AppBundle:Customer:index, token:nonexist }

customer_display_contract:
    path:   /e-contract/{token}/{dob}
    defaults: { _controller: AppBundle:Customer:displayContract, token:nonexist, dob:dob }
    
customer_accessdenied:
    path:   /access-denied/{ip}/{error}
    defaults: { _controller: AppBundle:Customer:accessDenied, ip:non, error:non }
    
customer_alreadysigned:
    path:   /already-signed/{ip}
    defaults: { _controller: AppBundle:Customer:alreadySigned, ip:non }
    
customer_signednote:
    path:   /signednote/{token}
    defaults: { _controller: AppBundle:Customer:signednote, token:token }
    
customer_ajaxsketch:
    path:   /customerajaxsketch
    defaults: { _controller: AppBundle:Customer:customerAjaxSketch }
    
customer_ajaxpreviewcontract:
    path:   /customerajaxpreviewcontract
    defaults: { _controller: AppBundle:Customer:customerAjaxPreviewContract }
    
customer_ajaxIframeView:
    path:   /ajaxIframeView
    defaults: { _controller: AppBundle:Customer:ajaxIframeView }
    
customer_about:
    path:   /about
    defaults: { _controller: AppBundle:Customer:about }
    
customer_contact:
    path:   /contact
    defaults: { _controller: AppBundle:Customer:contact }
    