<?php

namespace AppBundle\Entity;

/**
 * BlacklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlacklistRepository extends \Doctrine\ORM\EntityRepository
{
}
