<?php

namespace AppBundle\Entity;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function autocomplete() {

        $qb = $this->createQueryBuilder('c')
                ->select('c.name', 'c.id', 'c.email', 'c.phone', 'c.dob')
                ->addOrderBy('c.id');
        return $qb->getQuery()
                        ->getResult();
    }
    
    public function countAll() {
        $qb = $this->createQueryBuilder('c')
                ->select('count(c)');

        return $qb->getQuery()
                        ->getSingleScalarResult();
    }
    
    public function findByLimitOffset($offset, $limit) {

        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.id', 'DESC')
                ->setFirstResult($offset)
                ->setMaxResults($limit);

        return $qb->getQuery()
                        ->getResult();
    }
    
    
    public function searchByName($name) {

        $qb = $this->createQueryBuilder('n');
        $result = $qb->select('n')
                ->where($qb->expr()->like('n.name', $qb->expr()->literal('%' . $name . '%')))
                ->setMaxResults(100)
                ->getQuery()
                ->getResult();
        return $result;
    }
    
    public function searchByEmail($email) {

        $qb = $this->createQueryBuilder('n');
        $result = $qb->select('n')
                ->where($qb->expr()->like('n.email', $qb->expr()->literal('%' . $email . '%')))
                ->setMaxResults(100)
                ->getQuery()
                ->getResult();
        return $result;
    }
}
