<?php

namespace AppBundle\Entity;

/**
 * EcontractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcontractRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll() {
        $qb = $this->createQueryBuilder('c')
                ->select('count(c)');

        return $qb->getQuery()
                        ->getSingleScalarResult();
    }
    
     public function findByLimitOffset($offset, $limit) {

        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.id', 'DESC')
                ->setFirstResult($offset)
                ->setMaxResults($limit);

        return $qb->getQuery()
                        ->getResult();
    }
    
    public function searchByName($name) {

        $qb = $this->createQueryBuilder('s');
        $result = $qb->select('s', 'n')
                ->leftjoin('s.client', 'n')
                ->where($qb->expr()->like('n.name', $qb->expr()->literal('%' . $name . '%')))
                ->setMaxResults(100)
                ->getQuery()
                ->getResult();
        return $result;
    }
    
    public function searchByReference($name) {

        $qb = $this->createQueryBuilder('n');
        $result = $qb->select('n')
                ->where($qb->expr()->like('n.reference', $qb->expr()->literal('%' . $name . '%')))
                ->setMaxResults(100)
                ->getQuery()
                ->getResult();
        return $result;
    }
}
