<?php

namespace AppBundle\Entity;

/**
 * IplogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IplogRepository extends \Doctrine\ORM\EntityRepository
{
}
