<?php

namespace AppBundle\Entity;

/**
 * SelfsignatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelfsignatureRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll() {
        $qb = $this->createQueryBuilder('c')
                ->select('count(c)');

        return $qb->getQuery()
                        ->getSingleScalarResult();
    }
    
    public function findByLimitOffset($offset, $limit) {

        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.id', 'DESC')
                ->setFirstResult($offset)
                ->setMaxResults($limit);

        return $qb->getQuery()
                        ->getResult();
    }
}
