<?php

namespace AppBundle\Entity;

/**
 * TemplatesettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplatesettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
